
INSERT INTO `sequence_generator`(`seq_name`,`seq_value`) select * from (select 'Category' as seq_name, 0 as seq_value) as tmp where not exists(select * from sequence_generator where seq_name = 'Category');
INSERT INTO `sequence_generator`(`seq_name`,`seq_value`) select * from (select 'IssuerBank' as seq_name, 14 as seq_value) as tmp where not exists(select * from sequence_generator where seq_name = 'IssuerBank');
INSERT INTO `sequence_generator`(`seq_name`,`seq_value`) select * from (select 'Manufacturer' as seq_name, 0 as seq_value) as tmp where not exists(select * from sequence_generator where seq_name = 'Manufacturer');
INSERT INTO `sequence_generator`(`seq_name`,`seq_value`) select * from (select 'Product' as seq_name, 0 as seq_value) as tmp where not exists(select * from sequence_generator where seq_name = 'Product');
INSERT INTO `sequence_generator`(`seq_name`,`seq_value`) select * from (select 'Model' as seq_name, 0 as seq_value) as tmp where not exists(select * from sequence_generator where seq_name = 'Model');
INSERT INTO `sequence_generator`(`seq_name`,`seq_value`) select * from (select 'Scheme' as seq_name, 0 as seq_value) as tmp where not exists(select * from sequence_generator where seq_name = 'Scheme');
INSERT INTO `sequence_generator`(`seq_name`,`seq_value`) select * from (select 'SchemeModel' as seq_name, 0 as seq_value) as tmp where not exists(select * from sequence_generator where seq_name = 'SchemeModel');
INSERT INTO `sequence_generator`(`seq_name`,`seq_value`) select * from (select 'SchemeModelTerminal' as seq_name, 0 as seq_value) as tmp where not exists(select * from sequence_generator where seq_name = 'SchemeModelTerminal');
INSERT INTO `sequence_generator`(`seq_name`,`seq_value`) select * from (select 'SerialNo' as seq_name, 0 as seq_value) as tmp where not exists(select * from sequence_generator where seq_name = 'SerialNo');
INSERT INTO `sequence_generator`(`seq_name`,`seq_value`) select * from (select 'Tenure' as seq_name, 0 as seq_value) as tmp where not exists(select * from sequence_generator where seq_name = 'Tenure');

INSERT INTO `data_move_keeper`(`table_name`,`time_stamp`) select * from (select 'Category' as table_name, null as time_stamp) as tmp where not exists(select * from data_move_keeper where table_name = 'Category');
INSERT INTO `data_move_keeper`(`table_name`,`time_stamp`) select * from (select 'IssuerBank' as table_name, null as time_stamp) as tmp where not exists(select * from data_move_keeper where table_name = 'IssuerBank');
INSERT INTO `data_move_keeper`(`table_name`,`time_stamp`) select * from (select 'Manufacturer' as table_name, null as time_stamp) as tmp where not exists(select * from data_move_keeper where table_name = 'Manufacturer');
INSERT INTO `data_move_keeper`(`table_name`,`time_stamp`) select * from (select 'Product' as table_name, null as time_stamp) as tmp where not exists(select * from data_move_keeper where table_name = 'Product');
INSERT INTO `data_move_keeper`(`table_name`,`time_stamp`) select * from (select 'Model' as table_name, null as time_stamp) as tmp where not exists(select * from data_move_keeper where table_name = 'Model');
INSERT INTO `data_move_keeper`(`table_name`,`time_stamp`) select * from (select 'Scheme' as table_name, null as time_stamp) as tmp where not exists(select * from data_move_keeper where table_name = 'Scheme');
INSERT INTO `data_move_keeper`(`table_name`,`time_stamp`) select * from (select 'SchemeModel' as table_name, null as time_stamp) as tmp where not exists(select * from data_move_keeper where table_name = 'SchemeModel');
INSERT INTO `data_move_keeper`(`table_name`,`time_stamp`) select * from (select 'SchemeModelTerminal' as table_name, null as time_stamp) as tmp where not exists(select * from data_move_keeper where table_name = 'SchemeModelTerminal');
INSERT INTO `data_move_keeper`(`table_name`,`time_stamp`) select * from (select 'SerialNo' as table_name, null as time_stamp) as tmp where not exists(select * from data_move_keeper where table_name = 'SerialNo');
INSERT INTO `data_move_keeper`(`table_name`,`time_stamp`) select * from (select 'Tenure' as table_name, null as time_stamp) as tmp where not exists(select * from data_move_keeper where table_name = 'Tenure');

INSERT INTO `categories`(`record_update_timestamp`,`category_code`,`bajaj_category_code`,`category_description`,`category_display_name`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`) 
select * from (select '2017-09-14 15:15:17' as record_update_timestamp, 'XXXXXXXXXXXXX' as category_code, 'DEFAULT' as bajaj_category_code, 'DEFAULT'as category_description,'DEFAULT' as category_display_name , 'config' as record_update_reason,
'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active) as tmp where not exists(select * from categories where category_code='XXXXXXXXXXXXX');

INSERT  INTO `emi_tenures`(`record_update_timestamp`,`emi_tenure_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_tenure_display_name`,`emi_tenure_months`) 
select * from (select '2017-09-14 15:15:24' as record_update_timestamp,'XXXXX' as emi_tenure_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user,TRUE as is_record_active,'1 Month' as emi_tenure_display_name,'1' as emi_tenure_months)
as tmp where not exists(select * from emi_tenures where emi_tenure_code = 'XXXXX');



INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-01 19:10:19' as record_update_timestamp,'ISB0000000012' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,12 as emi_bank_code,'BAJAJ BANK' as issuer_bank_description,'BAJAJ BANK' as issuer_bank_disclaimer,'BAJAJ BANK' as issuer_bank_display_name ,'NA' as issuer_default_cashback_flag, 0 as issuer_min_emi_amount,'BAJAJ Terms and Conditions' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000012');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-14 15:15:18' as record_update_timestamp,'XXXXXXXXXXXXX' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,0 as emi_bank_code,'DEFAULT BANK' as issuer_bank_description,'DEFAULT Disclaimer' as issuer_bank_disclaimer,'DEFAULT' as issuer_bank_display_name ,'PRE' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'DEFAULT Terms and Conditions' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'XXXXXXXXXXXXX');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000001' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,1 as emi_bank_code,'HDFC Bank' as issuer_bank_description,'HDFC BANK Disclaimer' as issuer_bank_disclaimer,'HDFC' as issuer_bank_display_name ,'PRE' as issuer_default_cashback_flag, 5600.00 as issuer_min_emi_amount,'HDFC Terms and Conditions' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000001');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000002' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,3 as emi_bank_code,'ICICI Bank' as issuer_bank_description,'ICICI Bank Disclaimers' as issuer_bank_disclaimer,'ICICI Bank' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 2655.00 as issuer_min_emi_amount,'ICICI Bank Terms and Conditions' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000002');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000003' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,2 as emi_bank_code,'AXIS Bank' as issuer_bank_description,'AXIS Bank' as issuer_bank_disclaimer,'AXIS Bank' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'AXIS Bank' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000003');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000004' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,4 as emi_bank_code,'UNIPAY BANK' as issuer_bank_description,'UNIPAY BANK' as issuer_bank_disclaimer,'UNIPAY BANK' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'UNIPAY BANK' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000004');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000005' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,5 as emi_bank_code,'CITIBANK' as issuer_bank_description,'CITI BANK' as issuer_bank_disclaimer,'CITI BANK' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'CITI BANK' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000005');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000006' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,6 as emi_bank_code,'STANDARD CHARTERED BANK' as issuer_bank_description,'STANDARD CHARTERED BANK' as issuer_bank_disclaimer,'STANDARD CHARTERED BANK' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'STANDARD CHARTERED BANK' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000006');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000007' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,7 as emi_bank_code,'HSBC BANK' as issuer_bank_description,'HSBC BANK' as issuer_bank_disclaimer,'HSBC BANK' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'HSBC BANK' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000007');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000008' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,8 as emi_bank_code,'KOTAK BANK ' as issuer_bank_description,'KOTAK BANK ' as issuer_bank_disclaimer,'KOTAK BANK ' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'KOTAK BANK ' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000008');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000009' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,9 as emi_bank_code,'SBI BANK' as issuer_bank_description,'SBI BANK' as issuer_bank_disclaimer,'SBI BANK' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'SBI BANK' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000009');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000010' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,10 as emi_bank_code,'AMEX BANK' as issuer_bank_description,'AMEX BANK' as issuer_bank_disclaimer,'AMEX BANK' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'AMEX BANK' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000010');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000011' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,11 as emi_bank_code,'INDUSIND BANK' as issuer_bank_description,'INDUSIND BANK' as issuer_bank_disclaimer,'INDUSIND BANK' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'INDUSIND BANK' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000011');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2017-09-15 19:38:51' as record_update_timestamp,'ISB0000000013' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,13 as emi_bank_code,'RBL BANK' as issuer_bank_description,'RBL BANK' as issuer_bank_disclaimer,'RBL BANK' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 5000.00 as issuer_min_emi_amount,'RBL BANK' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000013');

INSERT INTO `issuer_banks` (`record_update_timestamp`,`issuer_bank_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`emi_bank_code`,`issuer_bank_description`,`issuer_bank_disclaimer`,`issuer_bank_display_name`,`issuer_default_cashback_flag`,`issuer_min_emi_amount`,`issuer_terms_conditions`) 
select * from ( select '2018-02-15 15:28:51' as record_update_timestamp,'ISB0000000014' as issuer_bank_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active ,14 as emi_bank_code,'YES BANK' as issuer_bank_description,'YES BANK' as issuer_bank_disclaimer,'YES BANK' as issuer_bank_display_name ,'POST' as issuer_default_cashback_flag, 2500.00 as issuer_min_emi_amount,'YES BANK' as issuer_terms_conditions)
as tmp where not exists(select * from issuer_banks where issuer_bank_code = 'ISB0000000014');

INSERT  INTO `issuer_schemes`(`record_update_timestamp`,`issuer_scheme_code`,`advance_emi`,`bajaj_issuer_scheme_code`,`bank_subvention`,`brand_subvention`,`issuer_cashback_flag`,`record_update_reason`,`record_update_status`,`record_update_user`,`general_scheme`,`innoviti_subvention`,`is_record_active`,`issuer_scheme_description`,`max_amount`,`merchant_subvention`,`min_amount`,`issuer_scheme_processing_fees`,`issuer_rate_of_interest`,`issuer_scheme_display_name`,`scheme_end_date`,`scheme_start_date`,`issuerBank_record_update_timestamp`,`issuer_bank_code`,`tenure_record_update_timestamp`,`emi_tenure_code`) 
select * from (select '2017-09-14 15:15:25' as record_update_timestamp,'XXXXXXXXXXXXX' as issuer_scheme_code,'1' advance_emi,'DEFAULT' as bajaj_issuer_scheme_code,'100.00FC' as bank_subvention,'200.00FU' as brand_subvention,'POST' as issuer_cashback_flag,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user,'GEN' as general_scheme,'300.00FU' as innoviti_subvention, TRUE as is_record_active,'DEFAULT' as issuer_scheme_description,'9999.99' as max_amount,'400.00FU' as merchant_subvention,'1111.11' as min_amount,'150.00F' as issuer_scheme_processing_fees,'8' as issuer_rate_of_interest,
'DEFAULT' as issuer_scheme_display_name,'2020-09-30 00:00:00' as scheme_end_date,'2017-09-15 00:00:00' as scheme_start_date,'2017-09-14 15:15:18' as issuerBank_record_update_timestamp,'XXXXXXXXXXXXX' as issuer_bank_code,'2017-09-14 15:15:24' as tenure_record_update_timestamp,'XXXXX' as emi_tenure_code)as tmp where not exists(select * from issuer_schemes where issuer_scheme_code = 'XXXXXXXXXXXXX');

INSERT  INTO `manufacturers`(`record_update_timestamp`,`manufacturer_code`,`bajaj_manufacturer_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`manufacturer_description`,`manufacturer_display_name`) 
select * from (select '2017-09-14 15:15:15' as record_update_timestamp,'XXXXXXXXXXXXX' as manufacturer_code,'DEFAULT' as bajaj_manufacturer_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user,TRUE as is_record_active,'DEFAULT' as manufacturer_description,'DEFAULT' as manufacturer_display_name)
as tmp where not exists (select * from manufacturers where manufacturer_code = 'XXXXXXXXXXXXX');

INSERT  INTO `products`(`record_update_timestamp`,`product_code`,`bajaj_product_type_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`product_type_code`,`is_record_active`,`issuer_product_display_name`) 
select * from (select '2017-09-14 15:15:16' as record_update_timestamp,'XXXXXXXXXXXXX' as product_code,'REMI' as bajaj_product_type_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user,'DEFAULT' as product_type_code, TRUE as is_record_active,'DEFAULT' as issuer_product_display_name)
as tmp where not exists (select * from products where product_code = 'XXXXXXXXXXXXX');

INSERT  INTO `models`(`record_update_timestamp`,`model_code`,`bajaj_model_code`,`bajaj_model_expiry_date`,`bajaj_model_number`,`bajaj_model_selling_price`,`record_update_reason`,`record_update_status`,`record_update_user`,`model_max_selling_price`,`model_min_selling_price`,`is_record_active`,`model_display_number`,`category_record_update_timestamp`,`category_code`,`manufacturer_record_update_timestamp`,`manufacturer_code`,`product_record_update_timestamp`,`product_code`) 
select * from(select '2017-09-14 15:20:20' as record_update_timestamp,'XXXXXXXXXXXXX' as model_code,'DEFAULT' as bajaj_model_code,'2099-01-01' as bajaj_model_expiry_date,'DEFAULT' as bajaj_model_number,'00000.00' as bajaj_model_selling_price,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user,'44444.00' as model_max_selling_price,'11111.00' as model_min_selling_price, TRUE as is_record_active,'DEFAULT' as model_display_number,'2017-09-14 15:15:17' as category_record_update_timestamp,
'XXXXXXXXXXXXX' as category_code,'2017-09-14 15:15:15' as manufacturer_record_update_timestamp,'XXXXXXXXXXXXX' as manufacturer_code,'2017-09-14 15:15:16' as product_record_update_timestamp,'XXXXXXXXXXXXX' as product_code) as tmp where not exists(select * from models where model_code = 'XXXXXXXXXXXXX');

INSERT  INTO `models`(`record_update_timestamp`,`model_code`,`bajaj_model_code`,`bajaj_model_expiry_date`,`bajaj_model_number`,`bajaj_model_selling_price`,`record_update_reason`,`record_update_status`,`record_update_user`,`model_max_selling_price`,`model_min_selling_price`,`is_record_active`,`model_display_number`,`category_record_update_timestamp`,`category_code`,`manufacturer_record_update_timestamp`,`manufacturer_code`,`product_record_update_timestamp`,`product_code`) 
select * from(select '2017-09-14 15:20:20' as record_update_timestamp,'XXXXXXXXXXGEN' as model_code,'DEFAULTGEN' as bajaj_model_code,'2099-01-01' as bajaj_model_expiry_date,'DEFAULT' as bajaj_model_number,'00000.00' as bajaj_model_selling_price,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user,'44444.00' as model_max_selling_price,'11111.00' as model_min_selling_price, TRUE as is_record_active,'DEFAULT' as model_display_number,'2017-09-14 15:15:17' as category_record_update_timestamp,
'XXXXXXXXXXXXX' as category_code,'2017-09-14 15:15:15' as manufacturer_record_update_timestamp,'XXXXXXXXXXXXX' as manufacturer_code,'2017-09-14 15:15:16' as product_record_update_timestamp,'XXXXXXXXXXXXX' as product_code) as tmp where not exists(select * from models where model_code = 'XXXXXXXXXXGEN');


INSERT  INTO `model_serial_numbers`(`record_update_timestamp`,`model_serial_number`,`manufacturer_model_serial_number`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_emi_used`,`is_record_active`,`model_record_update_timestamp`,`model_code`) 
select * from (select '2017-09-14 15:20:25' as record_update_timestamp,'XXXXXXXXXXXXX' as model_serial_number,'DEFAULT' as manufacturer_model_serial_number,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user ,TRUE as is_emi_used, TRUE as is_record_active,'2017-09-14 15:20:20' as model_record_update_timestamp,'XXXXXXXXXXXXX' as model_code)
as tmp where not exists (select * from model_serial_numbers where model_serial_number = 'XXXXXXXXXXXXX');

INSERT  INTO `issuer_scheme_model`(`record_update_timestamp`,`issuer_scheme_model_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`is_record_active`,`model_record_update_timestamp`,`model_code`,`scheme_record_update_timestamp`,`issuer_scheme_code`) 
select * from (select '2017-09-14 15:15:30' as record_update_timestamp,'XXXXXXXXXXXXX' as issuer_scheme_model_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user, TRUE as is_record_active,'2017-09-14 15:20:20' as model_record_update_timestamp,'XXXXXXXXXXXXX' as model_code,'2017-09-14 15:15:25' as scheme_record_update_timestamp,'XXXXXXXXXXXXX' as issuer_scheme_code)
as tmp where not exists (select * from issuer_scheme_model where issuer_scheme_model_code = 'XXXXXXXXXXXXX');

INSERT  INTO `issuer_scheme_model_terminal`(`record_update_timestamp`,`utid`,`bajaj_product_type_code`,`record_update_reason`,`record_update_status`,`record_update_user`,`dealer_id`,`is_record_active`,`issuer_custom_field`,`issuer_scheme_terminal_sync_status`,`issuer_scheme_onus_offus`,`fk_scheme_model_date`,`issuer_scheme_model_code`)
select * from (select '2017-09-14 15:15:50' as record_update_timestamp,'10010001' as utid,'DEFAULT' as bajaj_product_type_code,'config' as record_update_reason,'N' as record_update_status,'admin' as record_update_user,'DEALER ID' as dealer_id, TRUE as is_record_active,'CUSTOM' as issuer_custom_field,'NOT_SENT' as issuer_scheme_terminal_sync_status,'OFF_US' as issuer_scheme_onus_offus,'2017-09-14 15:15:30' as fk_scheme_model_date,'XXXXXXXXXXXXX' as issuer_scheme_model_code)
as tmp where not exists (select * from issuer_scheme_model_terminal where utid = '10010001');    
